(TeX-add-style-hook
 "appendices"
 (lambda ()
   (LaTeX-add-labels
    "sec:appendix-proofs"
    "def:conv-hull"
    "eq:conv-hull"
    "def:aff-hull"
    "eq:aff-hull"
    "def:relative-interior"
    "eq:relative-interior"
    "def:relative-boundary"
    "eq:relative-boundary"
    "alg:experiment-agnostic"
    "alg:experiment-realisable"
    "figs:agnostic-regression-learning-curves"
    "fig:learning-curve-agnostic-bike-sharing"
    "fig:learning-curve-agnostic-boston"
    "fig:learning-curve-agnostic-concrete"
    "fig:learning-curve-agnostic-red_whine"
    "fig:learning-curve-agnostic-white_wine"
    "figs:realisable-regression-learning-curves"
    "fig:learning-curve-realisable-bike-sharing"
    "fig:learning-curve-realisable-boston"
    "fig:learning-curve-realisable-concrete"
    "fig:learning-curve-realisable-red_whine"
    "fig:learning-curve-realisable-white_wine"
    "figs:agnostic-classification-learning-curves"
    "fig:learning-curve-agnostic-mnist"
    "fig:learning-curve-agnostic-yeast"))
 :latex)

